/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package videoclub;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Admin
 */
public class PanneauProgramme extends javax.swing.JPanel {
    private Cinema cinema;
    private boolean modifie;

    private DefaultComboBoxModel<Film> modeleFilms
            = new DefaultComboBoxModel<Film>();

    private DefaultComboBoxModel<Salle> modeleSalles
            = new DefaultComboBoxModel<Salle>();

    private DefaultComboBoxModel<Seance> modeleSeances
            = new DefaultComboBoxModel<Seance>();
    /**
     * Creates new form PanneauProgramme
     */
    public PanneauProgramme() {
        initComponents();
    }
    public PanneauProgramme(Cinema cinema) {
        initComponents();
        this.cinema = cinema;

        films.setModel(modeleFilms);
        salles.setModel(modeleSalles);
        seances.setModel(modeleSeances);

        actualiser();
    }
    public void actualiser() {
        Film filmChoisi = (Film) films.getSelectedItem();
        Salle salleChoisie = (Salle) salles.getSelectedItem();

        modeleFilms.removeAllElements();
        for (Film film : cinema.getFilms()) {
            modeleFilms.addElement(film);
        }

        if (cinema.getFilms().contains(filmChoisi)) {
            films.setSelectedItem(filmChoisi);
        }

        modeleSalles.removeAllElements();
        for (Salle salle : cinema.getSalles()) {
            modeleSalles.addElement(salle);
        }

        if (cinema.getSalles().contains(salleChoisie)) {
            salles.setSelectedItem(salleChoisie);
        }

        modeleSeances.removeAllElements();
        for (Seance seance : cinema.getSeances()) {
            modeleSeances.addElement(seance);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulaires = new javax.swing.JPanel();
        formulaireFilm = new javax.swing.JPanel();
        champsFilm = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        titre = new javax.swing.JTextField();
        Genre = new javax.swing.JLabel();
        genre = new javax.swing.JTextField();
        Durée = new javax.swing.JLabel();
        duree = new javax.swing.JTextField();
        listeFilms = new javax.swing.JPanel();
        ajouterFilm = new javax.swing.JButton();
        label_choix = new javax.swing.JLabel();
        films = new javax.swing.JComboBox<>();
        supprimerFilm = new javax.swing.JButton();
        formulaireSalle = new javax.swing.JPanel();
        champsSalle = new javax.swing.JPanel();
        numero = new javax.swing.JLabel();
        numeroSalle = new javax.swing.JTextField();
        rangee = new javax.swing.JLabel();
        lignes = new javax.swing.JTextField();
        sieges = new javax.swing.JLabel();
        colonnes = new javax.swing.JTextField();
        listeSalles = new javax.swing.JPanel();
        ajouterSalle = new javax.swing.JButton();
        label_salle = new javax.swing.JLabel();
        salles = new javax.swing.JComboBox<>();
        formulaireSeance = new javax.swing.JPanel();
        champsSeance = new javax.swing.JPanel();
        label_date = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        label_heure = new javax.swing.JLabel();
        heure = new javax.swing.JTextField();
        label_tarif = new javax.swing.JLabel();
        tarif = new javax.swing.JTextField();
        boutonsSeance = new javax.swing.JPanel();
        label_dhseance = new javax.swing.JLabel();
        ajouterSeance = new javax.swing.JButton();
        bas = new javax.swing.JPanel();
        programme = new javax.swing.JPanel();
        seances = new javax.swing.JComboBox<>();
        supprimerSeance = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout(10, 10));

        formulaires.setLayout(new java.awt.GridLayout(1, 3, 12, 0));

        formulaireFilm.setBorder(javax.swing.BorderFactory.createTitledBorder("1 - Films"));
        formulaireFilm.setLayout(new java.awt.BorderLayout(5, 10));

        champsFilm.setLayout(new java.awt.GridLayout(3, 2, 5, 10));

        Titre.setText("Titre");
        champsFilm.add(Titre);
        champsFilm.add(titre);

        Genre.setText("Genre");
        champsFilm.add(Genre);
        champsFilm.add(genre);

        Durée.setText("Durée (minutes)");
        champsFilm.add(Durée);
        champsFilm.add(duree);

        formulaireFilm.add(champsFilm, java.awt.BorderLayout.NORTH);

        listeFilms.setLayout(new java.awt.GridLayout(4, 1, 5, 10));

        ajouterFilm.setText("Ajouter le film");
        ajouterFilm.addActionListener(this::ajouterFilmActionPerformed);
        listeFilms.add(ajouterFilm);

        label_choix.setText("Film choisi pour la séance");
        listeFilms.add(label_choix);

        listeFilms.add(films);

        supprimerFilm.setText("Retirer le film choisi");
        supprimerFilm.addActionListener(this::supprimerFilmActionPerformed);
        listeFilms.add(supprimerFilm);

        formulaireFilm.add(listeFilms, java.awt.BorderLayout.SOUTH);

        formulaires.add(formulaireFilm);

        formulaireSalle.setBorder(javax.swing.BorderFactory.createTitledBorder("2 - Salle"));
        formulaireSalle.setLayout(new java.awt.BorderLayout(5, 10));

        champsSalle.setLayout(new java.awt.GridLayout(3, 2, 5, 10));

        numero.setText("Numéro");
        champsSalle.add(numero);
        champsSalle.add(numeroSalle);

        rangee.setText("Rangées (1 à 26)");
        champsSalle.add(rangee);
        champsSalle.add(lignes);

        sieges.setText("Sièges/rangée (1 à 50)");
        champsSalle.add(sieges);
        champsSalle.add(colonnes);

        formulaireSalle.add(champsSalle, java.awt.BorderLayout.NORTH);

        listeSalles.setLayout(new java.awt.GridLayout(3, 1, 5, 10));

        ajouterSalle.setText("Ajouter la salle");
        ajouterSalle.addActionListener(this::ajouterSalleActionPerformed);
        listeSalles.add(ajouterSalle);

        label_salle.setText("Salle utilisée pour la séance");
        listeSalles.add(label_salle);
        listeSalles.add(salles);

        formulaireSalle.add(listeSalles, java.awt.BorderLayout.SOUTH);

        formulaires.add(formulaireSalle);

        formulaireSeance.setBorder(javax.swing.BorderFactory.createTitledBorder("3 - Seance"));
        formulaireSeance.setLayout(new java.awt.BorderLayout(5, 10));

        champsSeance.setLayout(new java.awt.GridLayout(3, 2, 5, 10));

        label_date.setText("Date (JJ/MM/AAAA)");
        champsSeance.add(label_date);
        champsSeance.add(date);

        label_heure.setText("Heure (HH:MM)");
        champsSeance.add(label_heure);
        champsSeance.add(heure);

        label_tarif.setText("Prix par place (EUR)");
        champsSeance.add(label_tarif);

        tarif.setText("9,50");
        champsSeance.add(tarif);

        formulaireSeance.add(champsSeance, java.awt.BorderLayout.NORTH);

        boutonsSeance.setLayout(new java.awt.GridLayout(2, 1, 5, 10));

        label_dhseance.setText("Date et heure de la séance | Fin de séance au plus tard minuit");
        boutonsSeance.add(label_dhseance);

        ajouterSeance.setText("Programmer la séance");
        ajouterSeance.addActionListener(this::ajouterSeanceActionPerformed);
        boutonsSeance.add(ajouterSeance);

        formulaireSeance.add(boutonsSeance, java.awt.BorderLayout.SOUTH);

        formulaires.add(formulaireSeance);

        add(formulaires, java.awt.BorderLayout.CENTER);

        bas.setLayout(new java.awt.BorderLayout(8, 16));

        programme.setLayout(new java.awt.BorderLayout(8, 8));

        programme.add(seances, java.awt.BorderLayout.CENTER);

        supprimerSeance.setText("Retirer la séance choisie");
        supprimerSeance.addActionListener(this::supprimerSeanceActionPerformed);
        programme.add(supprimerSeance, java.awt.BorderLayout.EAST);

        bas.add(programme, java.awt.BorderLayout.NORTH);

        message.setText("Commence par un film et une salle, puis programme une séance.");
        bas.add(message, java.awt.BorderLayout.SOUTH);

        add(bas, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterFilmActionPerformed
        try {
            Film film = new Film(
                    titre.getText().trim(),
                    Integer.parseInt(duree.getText().trim()),
                    genre.getText().trim());

            cinema.ajouterFilm(film);
            actualiser();
            films.setSelectedItem(film);

            titre.setText("");
            genre.setText("");
            duree.setText("");

            message.setText("Film ajouté : " + film.getTitre());
            modifie = true;

        } catch (NumberFormatException e) {
            message.setText("Vérifie la durée saisie.");

        } catch (IllegalArgumentException e) {
            message.setText(e.getMessage());
        }
    }//GEN-LAST:event_ajouterFilmActionPerformed
    private void supprimerFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerFilmActionPerformed
        try {
            Film film = (Film) films.getSelectedItem();
            cinema.supprimerFilm(film);

            actualiser();
            message.setText("Le film a été retiré.");
            modifie = true;

        } catch (IllegalArgumentException e) {
            message.setText(e.getMessage());
        }
    }//GEN-LAST:event_supprimerFilmActionPerformed
    private void ajouterSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterSalleActionPerformed
        try {
            Salle salle = new Salle(
                    Integer.parseInt(numeroSalle.getText().trim()),
                    Integer.parseInt(lignes.getText().trim()),
                    Integer.parseInt(colonnes.getText().trim()));

            cinema.ajouterSalle(salle);
            actualiser();
            salles.setSelectedItem(salle);

            numeroSalle.setText("");
            lignes.setText("");
            colonnes.setText("");

            message.setText("La salle " + salle.getNumero() + " est prête.");
            modifie = true;

        } catch (NumberFormatException e) {
            message.setText("Vérifie les nombres saisis pour la salle.");

        } catch (IllegalArgumentException e) {
            message.setText(e.getMessage());
        }
    }//GEN-LAST:event_ajouterSalleActionPerformed
    private void ajouterSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterSeanceActionPerformed
        try {
            double prix = Double.parseDouble(
                    tarif.getText().trim().replace(',', '.'));

            Film film = (Film) films.getSelectedItem();
            Salle salle = (Salle) salles.getSelectedItem();

            Seance seance = new Seance(
                    film,
                    salle,
                    date.getText(),
                    heure.getText(),
                    prix);

            cinema.ajouterSeance(seance);
            actualiser();
            seances.setSelectedItem(seance);

            date.setText("");
            heure.setText("");

            message.setText(
                    "Séance ajoutée. Tu peux maintenant réserver des places.");
            modifie = true;

        } catch (NumberFormatException e) {
            message.setText(
                    "Vérifie le tarif saisi. Exemple : 9,50.");

        } catch (IllegalArgumentException e) {
            message.setText(e.getMessage());
        }
    }//GEN-LAST:event_ajouterSeanceActionPerformed
    private void supprimerSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerSeanceActionPerformed
        try {
            Seance seance = (Seance) seances.getSelectedItem();
            cinema.supprimerSeance(seance);

            actualiser();
            message.setText("La séance a été retirée.");
            modifie = true;

        } catch (IllegalArgumentException e) {
            message.setText(e.getMessage());
        }
    }//GEN-LAST:event_supprimerSeanceActionPerformed
    public boolean estModifie() {
        return modifie;
    }

    public void marquerEnregistre() {
        modifie = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Durée;
    private javax.swing.JLabel Genre;
    private javax.swing.JLabel Titre;
    private javax.swing.JButton ajouterFilm;
    private javax.swing.JButton ajouterSalle;
    private javax.swing.JButton ajouterSeance;
    private javax.swing.JPanel bas;
    private javax.swing.JPanel boutonsSeance;
    private javax.swing.JPanel champsFilm;
    private javax.swing.JPanel champsSalle;
    private javax.swing.JPanel champsSeance;
    private javax.swing.JTextField colonnes;
    private javax.swing.JTextField date;
    private javax.swing.JTextField duree;
    private javax.swing.JComboBox<Film> films;
    private javax.swing.JPanel formulaireFilm;
    private javax.swing.JPanel formulaireSalle;
    private javax.swing.JPanel formulaireSeance;
    private javax.swing.JPanel formulaires;
    private javax.swing.JTextField genre;
    private javax.swing.JTextField heure;
    private javax.swing.JLabel label_choix;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_dhseance;
    private javax.swing.JLabel label_heure;
    private javax.swing.JLabel label_salle;
    private javax.swing.JLabel label_tarif;
    private javax.swing.JTextField lignes;
    private javax.swing.JPanel listeFilms;
    private javax.swing.JPanel listeSalles;
    private javax.swing.JLabel message;
    private javax.swing.JLabel numero;
    private javax.swing.JTextField numeroSalle;
    private javax.swing.JPanel programme;
    private javax.swing.JLabel rangee;
    private javax.swing.JComboBox<Salle> salles;
    private javax.swing.JComboBox<Seance> seances;
    private javax.swing.JLabel sieges;
    private javax.swing.JButton supprimerFilm;
    private javax.swing.JButton supprimerSeance;
    private javax.swing.JTextField tarif;
    private javax.swing.JTextField titre;
    // End of variables declaration//GEN-END:variables
}
