/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package videoclub;
import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Admin
 */
public class FenetreCinema extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreCinema.class.getName());
    private Cinema cinema;
    private File fichier = new File("videoclub.dat");
    private PanneauProgramme programme;
    private PanneauReservations reservations;
    
    /**
     * Creates new form FenetreCinema
     */
    public FenetreCinema() {
        initComponents();
        setSize(1100, 680);

        cinema = new Cinema();
        if (fichier.exists()) {
            try {
                cinema = Sauvegarde.charger(fichier);
                message.setText("La dernière sauvegarde a été chargée.");
            } catch (IOException e) {
                message.setText("Sauvegarde illisible. Le cinéma est vide, le fichier est conservé.");
            } catch (ClassNotFoundException e) {
                message.setText("Sauvegarde incompatible avec cette version de VideoClub.");
        }
        } else {
            message.setText("Bienvenue dans VideoClub. Crée ton programme pour commencer.");
    }

    creerPanneaux();
    afficher(programme);    
    }
    
    private void creerPanneaux() {
    programme = new PanneauProgramme(cinema);
    reservations = new PanneauReservations(cinema);
}
    private void afficher(JPanel panneau) {
    contenu.removeAll();
    contenu.add(panneau, BorderLayout.CENTER);
    contenu.revalidate();
    contenu.repaint();
}
    private boolean estModifie() {
    return programme.estModifie() || reservations.estModifie();
}
    private boolean sauvegarder() {
        try {
            Sauvegarde.enregistrer(cinema, fichier);
            programme.marquerEnregistre();
            reservations.marquerEnregistre();
            message.setText("Sauvegarde effectuée dans " + fichier.getAbsolutePath());
            return true;
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Impossible de sauvegarder : " + e.getMessage(),
                    "Sauvegarde", JOptionPane.ERROR_MESSAGE);
            return false;
        }
}
    private void recharger() {
        if (estModifie()) {
            int reponse = JOptionPane.showConfirmDialog(this,
                    "Recharger remplacera les modifications non sauvegardées. Continuer ?",
                    "Recharger", JOptionPane.YES_NO_OPTION);
            if (reponse != JOptionPane.YES_OPTION) {
                return;
            }
        }

        try {
            Cinema copie = Sauvegarde.charger(fichier);
            cinema = copie;
            creerPanneaux();
            afficher(programme);
            message.setText("Sauvegarde rechargée.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Impossible de recharger : " + e.getMessage(),
                    "Recharger", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this,
                    "Ce fichier vient d'une version incompatible.",
                    "Recharger", JOptionPane.ERROR_MESSAGE);
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barre = new javax.swing.JPanel();
        Txt_VC = new javax.swing.JLabel();
        voirProgramme = new javax.swing.JButton();
        voirReservations = new javax.swing.JButton();
        enregistrer = new javax.swing.JButton();
        charger = new javax.swing.JButton();
        contenu = new javax.swing.JPanel();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VideoClub");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Txt_VC.setText("VidéoClub");
        barre.add(Txt_VC);

        voirProgramme.setText("Programme");
        voirProgramme.addActionListener(this::voirProgrammeActionPerformed);
        barre.add(voirProgramme);

        voirReservations.setText("Réservations");
        voirReservations.addActionListener(this::voirReservationsActionPerformed);
        barre.add(voirReservations);

        enregistrer.setText("Sauvegarder");
        enregistrer.addActionListener(this::enregistrerActionPerformed);
        barre.add(enregistrer);

        charger.setText("Recharger");
        charger.addActionListener(this::chargerActionPerformed);
        barre.add(charger);

        getContentPane().add(barre, java.awt.BorderLayout.PAGE_START);

        contenu.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contenu, java.awt.BorderLayout.PAGE_END);

        message.setText(" ");
        getContentPane().add(message, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voirProgrammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirProgrammeActionPerformed
        programme.actualiser();
        afficher(programme);
    }//GEN-LAST:event_voirProgrammeActionPerformed

    private void voirReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirReservationsActionPerformed
        reservations.actualiser();
        afficher(reservations);
    }//GEN-LAST:event_voirReservationsActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        sauvegarder();
    }//GEN-LAST:event_enregistrerActionPerformed

    private void chargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargerActionPerformed
        recharger();
    }//GEN-LAST:event_chargerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (estModifie()) {
            int reponse = JOptionPane.showConfirmDialog(this,
                    "Sauvegarder les modifications avant de quitter ?",
                    "Quitter VideoClub", JOptionPane.YES_NO_CANCEL_OPTION);
            
            if (reponse == JOptionPane.CANCEL_OPTION
                    || reponse == JOptionPane.CLOSED_OPTION) {
                return;
            }
            if (reponse == JOptionPane.YES_OPTION && !sauvegarder()) {
                return;
            }
        }
    dispose();
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Txt_VC;
    private javax.swing.JPanel barre;
    private javax.swing.JButton charger;
    private javax.swing.JPanel contenu;
    private javax.swing.JButton enregistrer;
    private javax.swing.JLabel message;
    private javax.swing.JButton voirProgramme;
    private javax.swing.JButton voirReservations;
    // End of variables declaration//GEN-END:variables
}