/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package videoclub;

/**
 *
 * @author Admin
 */
public class PanneauProgramme extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanneauProgramme.class.getName());

    /**
     * Creates new form PanneauProgramme
     */
    public PanneauProgramme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulaires = new javax.swing.JPanel();
        formulaireFilm = new javax.swing.JPanel();
        champsFilm = new javax.swing.JPanel();
        titre = new javax.swing.JTextField();
        genre = new javax.swing.JTextField();
        duree = new javax.swing.JTextField();
        listeFilms = new javax.swing.JPanel();
        ajouterFilm = new javax.swing.JButton();
        label_choix = new javax.swing.JLabel();
        films = new javax.swing.JComboBox<>();
        supprimerFilm = new javax.swing.JButton();
        formulaireSalle = new javax.swing.JPanel();
        champsSalle = new javax.swing.JPanel();
        numeroSalle = new javax.swing.JTextField();
        lignes = new javax.swing.JTextField();
        colonnes = new javax.swing.JTextField();
        listeSalles = new javax.swing.JPanel();
        ajouterSalle = new javax.swing.JButton();
        label_salle = new javax.swing.JLabel();
        salles = new javax.swing.JComboBox<>();
        formulaireSeance = new javax.swing.JPanel();
        champsSeance = new javax.swing.JPanel();
        date = new javax.swing.JTextField();
        tarif = new javax.swing.JTextField();
        boutonsSeance = new javax.swing.JPanel();
        bas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formulaires.setLayout(new java.awt.GridLayout(1, 3));

        formulaireFilm.setLayout(new java.awt.BorderLayout());

        champsFilm.setLayout(new java.awt.GridLayout(3, 2));

        titre.setText("Titre");
        champsFilm.add(titre);

        genre.setText("Genre");
        champsFilm.add(genre);

        duree.setText("Durée (minutes)");
        champsFilm.add(duree);

        formulaireFilm.add(champsFilm, java.awt.BorderLayout.CENTER);

        listeFilms.setLayout(new java.awt.GridLayout(4, 1));

        ajouterFilm.setText("Ajouter le film");
        listeFilms.add(ajouterFilm);

        label_choix.setText("Film choisi pour la séance");
        listeFilms.add(label_choix);

        films.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listeFilms.add(films);

        supprimerFilm.setText("Retirer le film choisi");
        listeFilms.add(supprimerFilm);

        formulaireFilm.add(listeFilms, java.awt.BorderLayout.PAGE_START);

        formulaires.add(formulaireFilm);

        formulaireSalle.setLayout(new java.awt.BorderLayout());

        champsSalle.setLayout(new java.awt.GridLayout(3, 2));

        numeroSalle.setText("Numéro");
        champsSalle.add(numeroSalle);

        lignes.setText("Rangées (1 à 26)");
        champsSalle.add(lignes);

        colonnes.setText("Sièges/rangée (1 à 50)");
        champsSalle.add(colonnes);

        formulaireSalle.add(champsSalle, java.awt.BorderLayout.CENTER);

        listeSalles.setLayout(new java.awt.GridLayout(3, 1));

        ajouterSalle.setText("Ajouter la salle");
        listeSalles.add(ajouterSalle);

        label_salle.setText("Salle pour la séance");
        listeSalles.add(label_salle);

        salles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listeSalles.add(salles);

        formulaireSalle.add(listeSalles, java.awt.BorderLayout.PAGE_START);

        formulaires.add(formulaireSalle);

        formulaireSeance.setLayout(new java.awt.BorderLayout());

        champsSeance.setLayout(new java.awt.GridLayout(3, 2));

        date.setText("Date (JJ/MM/AAAA)");
        date.addActionListener(this::dateActionPerformed);
        champsSeance.add(date);

        tarif.setText("9,50");
        tarif.setToolTipText("");
        champsSeance.add(tarif);

        formulaireSeance.add(champsSeance, java.awt.BorderLayout.CENTER);

        boutonsSeance.setLayout(new java.awt.GridLayout(2, 1));
        formulaireSeance.add(boutonsSeance, java.awt.BorderLayout.PAGE_START);

        formulaires.add(formulaireSeance);

        getContentPane().add(formulaires, java.awt.BorderLayout.CENTER);

        bas.setLayout(new java.awt.BorderLayout());
        getContentPane().add(bas, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PanneauProgramme().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterFilm;
    private javax.swing.JButton ajouterSalle;
    private javax.swing.JPanel bas;
    private javax.swing.JPanel boutonsSeance;
    private javax.swing.JPanel champsFilm;
    private javax.swing.JPanel champsSalle;
    private javax.swing.JPanel champsSeance;
    private javax.swing.JTextField colonnes;
    private javax.swing.JTextField date;
    private javax.swing.JTextField duree;
    private javax.swing.JComboBox<String> films;
    private javax.swing.JPanel formulaireFilm;
    private javax.swing.JPanel formulaireSalle;
    private javax.swing.JPanel formulaireSeance;
    private javax.swing.JPanel formulaires;
    private javax.swing.JTextField genre;
    private javax.swing.JLabel label_choix;
    private javax.swing.JLabel label_salle;
    private javax.swing.JTextField lignes;
    private javax.swing.JPanel listeFilms;
    private javax.swing.JPanel listeSalles;
    private javax.swing.JTextField numeroSalle;
    private javax.swing.JComboBox<String> salles;
    private javax.swing.JButton supprimerFilm;
    private javax.swing.JTextField tarif;
    private javax.swing.JTextField titre;
    // End of variables declaration//GEN-END:variables
}
